Pull Request for the 2nd milestone within the overall Tic Tac Toe project
jose-Abel/Tic-Tac-Toe-project pull request #2
Opened 2020-09-19 13:29 UTC by jose-Abel

Hello,

This is the Pull Request for the 2nd milestone within the Tic Tac Toe project where I have to display prompts for the users, collect user input, and only mock the basic flow of the game. I wasn't sure how long should go on the mock of the game.

Thanks for the feedback and happy coding!

2020-09-21 20:07 UTC, bertil291utn requested changes
# **Status:** Changes requested 🟠 
<p align="center"> <img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="60" /> <br><strong>Not yet</strong> </p>

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

### Your work is amazing you master it GitHub Flow you have a professional README file. 

However, in order to accomplish all the [requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/), you required to do these changes, listed below:


* [x] `[REQUIRED]` game displays board after the player move
* [x] `[REQUIRED]` game informs player if the selected move is a winning move
* [x] `[REQUIRED]` game informs player if the selected move is a draw move
* [x] `[REQUIRED]` game repeats all actions for the next player's move

### Summary
- Remember guys your code should not work yet, that's for the next milestone, for this one you could just add as inline comments or mocking up the methods. Example
```ruby
def validMove?(player)
  value=false
  value=true if player.move
value
end
```
-  Don't forget to work with inline comments below this comment box.

***

Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-09-21 20:07 UTC, bertil291utn commented on bin/main.rb
> +end
## Use static variables
- [ ] I'd suggest using static variables that already have winning moves, and then use `my_array.any` property to check that if just one array group has all these numbers there's a winner 
Example
```ruby
winning_moves=[[1,2,3],[3,5,7],[1,5,9]...]
```

2020-09-22 11:54 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Abel Ramirez Frontany** 
Great with your first submission for this project :muscle:  :muscle: 
We still need to fix some details:

- [ ] Your game must choose the board whenever the position is updated for a valid user movement.
- [x] You must validation the name of the two users are different
- [ ] You must validate the name of the users contains at least one character
- [x] You should favor the division of your code in different functions and files. Create at least one class for the basic functions of your game, save your class in the lib folder.
- [x] Use OOP concepts, your project should have classes (at least one), private methods, and attribute accessors.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-09-22 18:47 UTC, jose-Abel commented
> ### Status: Changes Required ♻️
> **Hello Abel Ramirez Frontany**
> Great with your first submission for this project 💪 💪
> We still need to fix some details:
> 
> * [x]  Your game must choose the board whenever the position is updated for a valid user movement.
> * [x]  You must validation the name of the two users are different
> * [x]  You must validate the name of the users contains at least one character
> * [x]  You should favor the division of your code in different functions and files. Create at least one class for the basic functions of your game, save your class in the lib folder.
> * [x]  Use OOP concepts, your project should have classes (at least one), private methods, and attribute accessors.
> 
> Please request another review once you are ready! 👍
> 
> Happy coding ☺️
> 
> Oscar Andrés Russi Porras

Hello, I'm trying to reach out to you through slack and it hasn't been successful. Among the improvements you mentioned is that I have to make different files and use more OOP concepts creating different classes and attribute. The thing is I know how to do that, but this milestone doesn't require those changes, keep in mind this is the user-interface milestone and I guess that those changes of making it more OOP are necessary for the game-logic milestone. Since this project has to be approved in phases, such that this user-interface milestone has to be approved separated from the game-logic milestone, I think you are requesting changes that are needed to get the next milestone approved. 

I appreciate a lot your feedback and would like to know if it's me that is mistaken. 

Best regards!

2020-09-23 00:32 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello Abel Ramirez Frontany** 
Great job with the improvements since the last review :muscle:  :muscle: 
Your project meets most of the requirements :clap: :clap: :clap:
And you are right, the OOP principles are not a requirement for the current milestone, my apologies. Still, there is one last detail to correct:

- [x] game should displays board after the player move (this is part of the checklist for this milestone).

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-09-23 17:46 UTC, bertil291utn approved these changes
# **Status:** Approved ✅

## Hey guys, you've been doing a great job, and also I hope you enjoyed coding.



<h2 align="center">Ship it </h2>

<p align="center"><img src="https://i.cubeupload.com/4HbSFK.jpg" alt="image" width="100" /></p>

Please merge to develop branch and move on with the next milestone

You're doing  a great job keep going 💻 🚀 🔥

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-09-23 17:58 UTC, merged