Pull Request for the 3rd milestone game-logic for the Tic Tac Toe Project
jose-Abel/Tic-Tac-Toe-project pull request #5
Opened 2020-09-25 19:47 UTC by jose-Abel

Hello, 

This is the Pull Request review for the 3rd milestone, game-logic, within the overall Tic Tac Toe Project. In this milestone, the codebase is changed from functional programming (having all in methods in the same file) to OOP programming where is created 2 classes and 1 module grouping together all the methods that belong to each class and the module. The created classes are:

- The Player class that initializes with 4 attributes, the strings name and mark, the array moves and the boolean has_won, the strings name and mark are parameters for the initialize method. This class also has 1 public method called winning_moves and 3 private methods horizontal_checking, vertical_checking, and diagonal_checking. The public method runs the private method to determine if the player has won the game. 

- The Board class that initializes a variable named positions that contains the hash for the key-value pairs of the board. It also has the public methods move_in_board in charge of adding the "X" or "O" mark value, depending on the player, to its respective key in the board. If the position has already been chosen or does not exist in the board this method does some validation on that and called the get_user_input methods located in main again so that the user can try with a different choice. The Board class also has the methods hash_has_blank to determine if the board has any key without any value and as soon as there isn't any key with an empty value the game stops. Finally, it has the paint_canvas method in charge of displaying the board with the user's marks, either 'X' or 'O', in its respective key.

- The HelperMethods module, with the 2 methods name_not_empty as the name implies it makes sure that the name field at the beginning is not left empty by either of the players and the repeated_name method in charge of making sure the second player doesn't choose the same name as the first.

- The main file is where everything happens, it has the main method where the board and the players are initialized, the players passing the name as the elements in the array that contains the called for the choice_your_player method located in the same file and the mark as 'X' or 'O'. The main file is also responsible for the core while loop that will keep running until either one of the players has_won property is set to true or the board hash_has_blank method returns false. The main file has the methods intro where the initial instructions are provided to the players and lastly it has the get_user_input method were, passing the player and the board arguments, is in charge of calling the move_in_board method for the board class on the board instance object. 

Hoping to get amazing feedback, happy coding!

2020-09-26 05:33 UTC, kitpao requested changes
# 👋 Hello @jose-Abel 

🌟 Nice welcome message and good job considering many validations 🏅 And your winning conditions all work 💯 

**_Note:_** All the **[OPTIONAL]** are **not required** in order to approve your project but are personal suggestions to improve your coding experience

- [x] **OPTIONAL** Woah! you made a detailed description of your classes in your pull request message, if you want, you can add it to your Readme so that anyone that wants to check your project, will be able to read about it. As a note, pull request messages don't need to be _that_ detailed.

- [x] Your commits are descriptive, but for next time try to be consistent and write your commits in the imperative tense, as stated in [the article pointed in pathwright](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8/)

- Remember all interaction with players (puts, print, get) should be in your main file, you used them in your Board, Helper, and Player files. Please take them out of there and use them in the main file. **Hint:** You can also make your methods return strings and then in the main file you write `puts method_name`.
![image](https://user-images.githubusercontent.com/53256139/94330000-9a23eb80-ff85-11ea-9605-171805f3f8bf.png)

- [x] **OPTIONAL** It would be nice if you displayed the board at the beginning of the game also

- [x] You have a bug where it displays a winning message for each time the input was not valid:
![image](https://user-images.githubusercontent.com/53256139/94330369-8c706500-ff89-11ea-8a97-f5b981cbc453.png)

- [x] Remember about the Single Responsibility Rule (part of SOLID principles in coding). When you have long methods usually mean that they are doing too many things and you can either separate them or refactor them. For example, your method choose_your_player handles the actions for 2 different players and repeats the same instructions for both, you can create 1 method that encapsulatesthe methods that a player must have, so you only have to call for 1 action for each player
![image](https://user-images.githubusercontent.com/53256139/94330571-32709f00-ff8b-11ea-97c1-fa1d2fffee8b.png)

### ♻️ Status: Your project requires some additional changes ♻️
➡️ Please request another review once you are ready 📝 
___
##### 👉 If you have any doubts you can contact me in slack as @kitpao
##### 🌟  If you have feedback about my reviews I would appreciate if can leave a recommendation in LinkedIn 💌 or let me know in Slack if you see improvements to be done 😛 

🔗 __[Github](https://github.com/kitpao) | [Twitter](https://twitter.com/Kitpao1) | [LinkedIn](https://www.linkedin.com/in/kitzia-paola-vidal/) | [Medium](https://medium.com/@kitpao91)__

2020-09-26 05:33 UTC, kitpao commented on lib/board.rb
> +# rubocop : disable Metrics/AbcSize
- [x] Please, do not skip that many rules in your project, if you skip them, there is not really much point in having the linters. Rubocop gives you messages so that you get the best practices when you are working with a team, please take this out and refactor your code, you can use variables to shorten line lengths, take into consideration the efficiency of your code for complexity, etc.

2020-09-26 05:33 UTC, kitpao commented on lib/helper.rb
> +  end
- [x] You have a bug after asking for a valid name for player 1 after giving an empty name, please check it out and fix it:
![image](https://user-images.githubusercontent.com/53256139/94330210-04d62680-ff88-11ea-8c40-fc261ff0ad4e.png)

2020-09-27 17:05 UTC, jose-Abel commented on lib/board.rb
> +# rubocop : disable Metrics/AbcSize
Did the changes requested, thanks for helping me to be a better programmer!

Best regards!

2020-09-27 17:59 UTC, kobiyoyo requested changes
## Hi Team   ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, everything works fine, but there are a few more things required. 
### General 
- [ ] You should add validations for player names, I can input integers.
- [ ] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [ ] Check comments below
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-09-27 17:59 UTC, kobiyoyo commented on lib/board.rb
> +  attr_accessor :positions
- [ ] You should use  attr_readers or attr_writers. Only using attr_accessors it allows writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-09-27 17:59 UTC, kobiyoyo commented on lib/player.rb
> +  attr_accessor :moves
- [ ] You should use  attr_readers or attr_writers. Only using attr_accessors it allows writing that property from outside the class. That variable can be set to anything. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/attr_accessor.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-09-27 19:50 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team  ,  you have done a brilliant job with this project. :clap:

#### You can merge Once you done with the minor changes below!!!

2020-09-27 19:50 UTC, kobiyoyo commented on lib/helper.rb
> +    puts
- [ ] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-09-27 19:50 UTC, kobiyoyo commented on lib/board.rb
> +    puts
- [ ] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

2020-09-27 20:02 UTC, merged